# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Run dbt Models

Trigger:
    push:
    branches:
      - main  # Change this to your main branch name

jobs:
  run-dbt:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: datafactz123/repo  # Corrected the repository URL

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt
          pip install dbt-snowflake

      - name: Create Environment File
        run: |
          echo 'C:\Users\skrishna\Desktop\DBT\dbt-env\Scripts' >> $GITHUB_PATH
          echo 'C:\Users\skrishna\.dbt' >> $GITHUB_PATH
          echo 'C:\Users\skrishna\Desktop\DBT\dbt-project\dfz' >> $GITHUB_PATH
          
      - name: Run dbt models
        run: |
          dbt run --profiles-dir C:\Users\skrishna\.dbt
          dbt run --project-dir C:\Users\skrishna\Desktop\DBT\dbt-project\dfz
