dfz:
  outputs:
    dev:
      account: proahry-rw38174
      database: DBT
      password: Welcome@123
      role: ACCOUNTADMIN
      schema: CORE
      threads: 4
      type: snowflake
      user: saikrishna
      warehouse: COMPUTE_WH
  target: dev
