name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Choose your Python version

      - name: Install dbt
        run: |
          pip install dbt
        shell: bash

      - name: Run dbt models
        run: |
          export DBT_PROJECT_PATH=/Users/skrishna/Desktop/DBT/dbt-project/dfz/dbt_project.yml
          dbt run
