name: schedule_dbt_run
on:
 push:
    branches:
    # run on push to main branch
    - main
    
jobs:
 schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: windows-latest

    steps:
    - name: Check out
      uses: actions/checkout@master
    - name: set up python 
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"

    - name: Install dependencies
      run: |
        pip install dbt
        dbt deps

    # dbt related commands here - run use --target prod/dev to run for specific environments
    - name: Run dbt models
      run: dbt run

    - name: Test dbt models
      run: dbt test
