name: Example Workflow

on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: windows-latest
    env:
      MY_ENV_VARIABLE: ${{ github.workspace }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print workspace path
        run: echo "Workspace Path ${{ github.workspace }}"
