name: Example Workflow

on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: windows-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print workspace path
        run: echo "Workspace Path ${{ https://github.com/datafactz123/repo.git }}"
