name: Run dbt Models

on:
  push:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: datafactz123/repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt
          pip install dbt-snowflake

      - name: Create Environment File
        run: |
          echo '${{ github.workspace }}\dbt-env\Scripts' >> $GITHUB_PATH
          echo '${{ github.workspace }}\.dbt' >> $GITHUB_PATH
          echo '${{ github.workspace }}\dbt-project\dfz' >> $GITHUB_PATH
          
      - name: Run dbt models
        run: |
          dbt run --profiles-dir ${{ github.workspace }}
