name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dbt and dependencies
        run: |
          pip install dbt
          # Add any additional dependencies if needed

      - name: Change to the project directory
        run: cd Users\skrishna\Desktop\DBT\dbt-project\dfz

      - name: Run dbt models
        run: dbt run
