name: Run dbt Models

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: datafactz123/repo  # Corrected the repository URL

      - name: Upload dfz directory
        uses: actions/upload-artifact@v2
        with:
          name: dfz-artifact
          path: dfz  # Adjust the path to your dfz directory

  run-dbt:
    needs: upload-artifact
    runs-on: windows-latest

    steps:
      - name: Download dfz directory
        uses: actions/download-artifact@v2
        with:
          name: dfz-artifact

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt
          pip install dbt-snowflake

      - name: Run dbt models
        run: |
          dbt run --select example/cust_info
