name: Run dbt Models

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  run-dbt:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          url: ${{ https://github.com/datafactz123/repo.git }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt==1.3.2
          pip install dbt-snowflake==1.1.0

      - name: Run dbt models
        run: dbt run --models "repo/dfz/models/example/cust_info.sql"
